services:
  web:
    image: webdevops/php-apache-dev:8.2-alpine
    container_name: api-laravel-back
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    user: "www-data"
    depends_on: 
      - dbpomodoro
      - websocket
    networks:
      - app-network

  dbpomodoro:
    image: mysql:8.3
    container_name: pomodoro-mysql
    volumes:
      - 'db:/var/lib/mysql/'
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    networks:
      - app-network

  websocket:
    image: webdevops/php-apache-dev:8.2-alpine
    container_name: laravel-websocket
    restart: always
    volumes:
      - ./:/app
    working_dir: /app
    command: php artisan reverb:start
    depends_on:
      - dbpomodoro
    networks:
      - app-network

volumes:
  db:
    driver: local

networks:
  app-network:
    driver: bridge